### ISSUE TITLE
Qt Version of sidebar ?

### ISSUE THREAD

**Issue by azzamsa** [eyllanesc/stackoverflow#13]
In Qt Designer, what is the best approach to do this ? 

https://github.com/eyllanesc/stackoverflow/tree/master/others/SideBar

**Comment by eyllanesc** [comment]
@azzamsa  Do you want me to translate this code to python?

**Comment by azzamsa** [comment]
No, No. I just wanna ask. What approach best to do this ?

1) make two layout in one widget ? 
2) or any other approach ?

**Comment by eyllanesc** [comment]
Actually there are several correct approaches, for example my version publish it when I start in Qt, now I use a QQuickWidget with a QML since the design is simpler, another option is to use a layout, and at least those that point out are correct for my.

**Comment by azzamsa** [comment]
![2019-02-27-19 08 41](https://user-images.githubusercontent.com/17734314/53489198-27117500-3ac3-11e9-9700-a436f73d6151.png)

My approach is to use 
1) two layout A and B, I use QStackedWidget for B, I still donno for A, how to make it presistent while B changed ?
2) use button and change it as image for sidebar.

**Comment by eyllanesc** [comment]
@azzamsa  Use a QVBoxLayout or a QFormLayout.

**Comment by azzamsa** [comment]
Thanks lot for help, I think I still need more research, still have no idea how to archive it. for now, I will stick to tabbed widget.

thanks for your time

![2019-02-27-19 25 10](https://user-images.githubusercontent.com/17734314/53490138-84a6c100-3ac5-11e9-9880-814b748eedb9.png)

**Comment by azzamsa** [comment]
Thank you. it solved now. I use widget container side-by-side and wrap them into layout. thanks.
