### ISSUE TITLE
A broken link in stackoverflow answer

### ISSUE THREAD

**Issue by BaseMax** [eyllanesc/stackoverflow#20]
Hello,

I found a broken link.
https://github.com/eyllanesc/stackoverflow/tree/master/questions/46007131-pyqt5-qtabwidget-make-every-tab-the-same-width-and-also-expandable

At: https://stackoverflow.com/questions/46007131/pyqt5-qtabwidget-make-every-tab-the-same-width-and-also-expandable

**ID: 46007131**
I found this page from your GitHub.

> If some of the links I have provided in my answers have been broken please post an issue in the repository. 

Best,
Max Base

**Comment by eyllanesc** [comment]
@BaseMax  Thanks
