### ISSUE TITLE
Ubuntu Qt Mysql connection issue 

### ISSUE THREAD

**Issue by sujith2014** [eyllanesc/stackoverflow#21]
Bro can you help me to solve an issue mentioned here https://forum.qt.io/topic/110086/qsqldatabase-qmysql-driver-not-loaded-ubuntu-qt5-14-0/2
Through Anydesk?
 please reply on sujith2014@gmaiil.com

**Comment by eyllanesc** [comment]
@sujith2014  Execute:

```
cd /home/sujith/Qt5.14.0/5.14.0/Src/qtbase/src/plugins/sqldrivers && /home/sujith/Qt5.14.0/5.14.0/gcc_64/bin/qmake sqldrivers.pro && make && make install
```
