### ISSUE TITLE
Broken link on StackOverflow

### ISSUE THREAD

**Issue by AwesomeCronk** [eyllanesc/stackoverflow#22]
Your link to your GitHub for [this question](https://stackoverflow.com/questions/44762549/trying-to-get-pyqt5-and-opengl-working) on StackOverflow is broken. I did, however, manage to find the code with some searching.

https://github.com/eyllanesc/stackoverflow/tree/584415610e547273ebed859378cb072c6a5e5b73/others/OpenglPyQtTest

**Comment by eyllanesc** [comment]
@AwesomeCronk  Thanks
