### ISSUE TITLE
Bug in answer for saving/restoring widget properties using QSettings

### ISSUE THREAD

**Issue by Zythyr** [eyllanesc/stackoverflow#26]
@eyllanesc Firstly thank you for the amazing support you have provided to me and another on PyQt. 

I am reporting an issues to one of your answers found on stackoverflow. Below are relevant links 
https://stackoverflow.com/a/60028282/4988010 
https://gist.github.com/eyllanesc/be8a476bb7038c7579c58609d7d0f031  

**Issue:** 
Using the save/restore functions you provided, I noticed a bug. Restoring settings from the ini file doesn't work properly. In an demo example I have created, the app contains multiple QDoubleSpinBox widgets. After restoring the settings, the resulting widgets have incorrect values. Often these incorrect values are duplicates of what another wQDoubleSpinBox widget contains. I can add screenshots of the issue if you're unable to reproduce. I tried troubleshoot the issue but still can't figure out why 
https://gist.github.com/Zythyr/930ed8ac09a830717a459349e942a86a 

I tried to troubleshoot the issue. When `w.setProperty(name, val)` is called, the `val` is correct as expected. But the actual written value is incorrect. I am unsure whats going on.

**Comment by eyllanesc** [comment]
@Zythyr  It seems that it is a bug of my solution since the logic was to save information of all the QObjects even the internal ones, and those internal elements were overridden the correct values. The solution is to change:

```python
if w.objectName():
```
to 

```python
if w.objectName() and not w.objectName().startswith("qt_"):
```

**Comment by Zythyr** [comment]
@eyllanesc Thanks for the fix. I have some follow up questions: 

1) Can you edit the answer on stackoverflow with the fixed bug https://stackoverflow.com/a/60028282/4988010 

2) I noticed another bug, at least on my specific use case. When I have multiple instances of my application running, restoring of settings doesn't work correctly. See my example code below where I have multiple instances of `MyApp()` running, where each app has a unique name thus also a unique config .ini file also. 

Although both apps have their own unique windows. When saving the settings in the ini, settings of the widgets from both apps are saved. Because the widgets have the same name, settings of one app overwrite the other. I think the issue arises from getting a list of all the widgets using `for w in QtWidgets.qApp.allWidgets():`. Therefore, is a way I can have the settings to a ini file that is unique to each application window and not the global qt app which may contain multiple windows (app instances)? 

```
# settings_restore  and settings_save have been excluded for simplicity 

class MyApp(QtWidgets.QMainWindow):
    
    def __init__(self, app_name='AppNameHere'):
        super(MyApp, self).__init__()
        
        self.settings = QSettings("./temp/gui_settings-{}.ini".format(app_name), QSettings.IniFormat)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowTitle(app_name)

        self.ui.action_config_save_current_values.triggered.connect(self.config_widgets_save_settings)
        self.ui.action_config_load_config_file.triggered.connect(self.config_widgets_load_settings)
        self.ui.action_config_reset_to_factory_default.triggered.connect(self.config_widgets_reset_settings)

    def config_widgets_save_settings(self):
        # Save settings 
        # self.logger.info('Saving current values of the widgets into a config file.')
        settings_save(self.settings)

    def config_widgets_load_settings(self):
        # self.logger.info('Loading saved widgets settings config file.')
        # Load previous usage settings 
        settings_restore(self.settings)

    def config_widgets_reset_settings(self):
        # self.logger.info('Resetting the saved widgets settings config file to default factor settings.')
        self.settings.clear()
        self.ui.setupUi(self)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    app_one = MyApp(app_name='App#1')
    app_one.show()
    
    app_two = MyApp(app_name='App#2')
    app_two.show()

    app.exec_()

```
