### ISSUE TITLE
Please help me to represent data from csv on map

### ISSUE THREAD

**Issue by robertique** [eyllanesc/stackoverflow#31]
Hi there!
eyllanesc, could you please help me to display markers (colored markers based on value) on map using a .csv file? 
I have several csv files which contains data as follow: latitude, longitude, 200 channels (with signal levels).
I used a data mining framework and I like the results, but I need a QT app.
Thanks a lot!
Data File  and Reprsentation on map 
![0](https://user-images.githubusercontent.com/77357755/107887727-d0501080-6f10-11eb-84ce-afc0fbad104e.png)
![1](https://user-images.githubusercontent.com/77357755/107887730-d3e39780-6f10-11eb-9049-cf5ec2c88600.png)
![2](https://user-images.githubusercontent.com/77357755/107887738-dfcf5980-6f10-11eb-8a35-c300bb554851.png)

**Comment by eyllanesc** [comment]
If you want me to implement any functionality then write to my email e.yllanescucho@gmail.com to agree on the cost, time, etc.
