### ISSUE TITLE
Question on Two List Selection 48327558

### ISSUE THREAD

**Issue by davidchik** [eyllanesc/stackoverflow#34]
Dear Edwin,

Sorry for bothering you. I am a newbie of using Qt.

I tried to use your Two List Selection in stackoverflow/questions/48327558 but in my application I already have a UI file. I renamed the object names of my pushButtons to match your names: mButtonToSelected; mBtnMoveToAvailable; mBtnMoveToSelected; mButtonToAvailable. However, I do not know how to modify lines 27-65 in your header file, so that it will follow my UI file instead of following your layout.

Would you kindly teach me how to do so? Thank you very much indeed.

Best Regards,
David

**Comment by eyllanesc** [comment]
@davidchik You have to give more detail if you want help, for example show the code you have and explain what part of the code causes the problem, not only indicate [the lines](https://github.com/eyllanesc/stackoverflow/blob/master/questions/48327558/twolistselection.h#L27-L65) but why it causes problems.

**Comment by davidchik** [comment]
I have solved the problem. I just need to change mInput to ui->mInput, mOuput to ui->mOuput, etc. Ha ha.
