### ISSUE TITLE
Example wont work with PySide2

### ISSUE THREAD

**Issue by dec1** [eyllanesc/stackoverflow#7]
The PandasTableView example wont work with the new official PySide2 from The Qt Company

**Comment by dec1** [comment]
would be solved by https://github.com/eyllanesc/stackoverflow/pull/8

**Comment by dec1** [comment]
First of all, thanks very much for the helpful example.


Secondly, my pull request improves your answer by removing the unnecessary use of QVariant, thereby making your answer simpler and easier to understand. As a free bonus it makes your example also compatible with PySide (which being from the QT company will likely replace PyQt). Even though this may not help the original poster of the question, do you really not want your answer to be able to help more users for "free", and keep your answer relevent for longer (if/even when most people switch to pyside)

**Comment by eyllanesc** [comment]
@dec1  I think you do not know the history of PySideX, and PyQtX. PySide is a binding of Qt4 that is not currently part of Qt officially. Qt is currently launching PySide2 as a binding of Qt5 and is getting off to a good start. riverbankcomputing also offers its bindings of Qt4 and Qt5 called PyQt4 and PyQt5, these libraries have commercial license and GPL, so the free is relative. I do not pretend to have a universal code necessarily, for that I would prefer to use QtPy or similar but this can be an extra effort that I do not want to do it. On the other hand, the current code that is an adaptation of my code from PyQt4 to PyQt5 has the QVariant, which is necessary in PyQt4, so it still remains and I do not want to change it. I appreciate your contribution but I think it is not necessary, as you have seen, you have easily translated it to PySide2, currently PySide2 is not very stable and you have numerous bugs so I do not choose it as my standard library.

**Comment by eyllanesc** [comment]
@dec1 In conclusion, PySide2 will not replace PyQt5, my answers are dependent on SO questions, they are a way to show extensive code that can not be or is ugly in OS, if the question needs support for other libraries I can do it, just I consider bugs of my answer if you have used the same libraries that the OP has used, or certain questions in which I can support other OS. :smile_cat:
